# Change these first
owner: cyscale # Your GitHub organization or username, where this repository lives
repo: status.cyscale.com # The name of this repository

sites:
  - name: Cyscale Website
    url: https://cyscale.com
  - name: Power Cloud Platform
    url: https://app.cyscale.com
  - name: Cyscale API
    url: https://api.cyscale.com
  - name: GraphQL API
    url: https://graphql.cyscale.com
  - name: Authentication API
    url: https://graphql.cyscale.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cyscale.com
  # baseUrl: /your-repo-name
  logoUrl: https://static-cyscale-com.s3.amazonaws.com/img/cyscale_logo.svg
  name: Cyscale uptime
  introTitle: "**Cyscale** - helping companies embrace their digital future by protecting apps & data in the cloud."
  introMessage: |
    This is the **real-time** status page for Cyscale. 
    
    **Try Cyscale Cloud Security for free: <https://cyscale.com>**
  navbar:
    - title: cyscale.com
      href: https://cyscale.com
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "cyscale-bot"
  commitAuthorEmail: "developers@cyscale.com"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
